import { lazy, Suspense, useMemo, useState } from 'react';
import { generateProblem } from './chemistry/generator'; import { checkAnswer } from './chemistry/checker'; import { loadProgress, record, resetProgress, saveProgress } from './chemistry/progress';
import { Structure } from './components/Structure'; import { DecisionGuide } from './components/DecisionGuide';
import { equivalentDrawnStructures } from './chemistry/structureValidation';
import type { AnswerMechanism, Difficulty, StudentAnswer } from './types';
import { problemBank } from './chemistry/problemBank';
const answerMechanisms: AnswerMechanism[]=['SN1','SN2','No reaction']; const mechanismOptions: (AnswerMechanism|'Mixed')[]=['Mixed',...answerMechanisms]; const difficulties:Difficulty[]=['Introductory','Intermediate','Challenge']; const concepts=['SN1 vs SN2','strong nucleophiles','weak nucleophiles','carbocation stability','polar aprotic solvent','no reaction'];
const KetcherProductEditor = lazy(() => import('./components/KetcherProductEditor').then(({ KetcherProductEditor }) => ({ default: KetcherProductEditor })));
export default function App(){const [page,setPage]=useState<'practice'|'guide'|'progress'>('practice');const [mechanism,setMechanism]=useState<AnswerMechanism|'Mixed'>('Mixed');const [difficulty,setDifficulty]=useState<Difficulty>('Introductory');const [selectedConcepts,setSelectedConcepts]=useState<string[]>([]);const [seed,setSeed]=useState(0);const problem=useMemo(()=>generateProblem({mechanism,difficulty,concepts:selectedConcepts,seed}),[mechanism,difficulty,selectedConcepts,seed]);const availableConcepts=useMemo(()=>new Set(problemBank.filter(p=>p.difficulty===difficulty&&(mechanism==='Mixed'||p.intendedMechanism===mechanism)).flatMap(p=>p.concepts)),[difficulty,mechanism]);const [answer,setAnswer]=useState<StudentAnswer>({});const [drawingGetter,setDrawingGetter]=useState<(() => Promise<string>)>();const [feedback,setFeedback]=useState<ReturnType<typeof checkAnswer>>();const [hint,setHint]=useState(0);const [progress,setProgress]=useState(loadProgress);
 const next=()=>{setSeed(x=>x+1);setAnswer({});setDrawingGetter(undefined);setFeedback(undefined);setHint(0)}; const submit=async()=>{const majorProducts=problem.products.filter(product=>product.role==='major');const expectedSmiles=problem.intendedMechanism==='No reaction'?[problem.substrateSmiles]:majorProducts.map(product=>product.smiles);const drawnSmiles=drawingGetter?await drawingGetter():'';const checkedAnswer=drawnSmiles?{...answer,productSmiles:drawnSmiles,productIsStructureEquivalent:await equivalentDrawnStructures(drawnSmiles,expectedSmiles)}:answer;setAnswer(checkedAnswer);const result=checkAnswer(problem,checkedAnswer);setFeedback(result);const updated=record(progress,problem,result.level==='correct');setProgress(updated);saveProgress(updated)};
 const chooseConcept=(c:string)=>setSelectedConcepts(x=>x.includes(c)?x.filter(y=>y!==c):[...x,c]);
 return <main><a className="skip" href="#content">Skip to practice content</a><header><div><p className="eyebrow">ORGANIC CHEMISTRY I</p><h1>Mechanism Lab</h1></div><nav aria-label="Primary"><button onClick={()=>setPage('practice')} aria-current={page==='practice'?'page':undefined}>Practice</button><button onClick={()=>setPage('guide')} aria-current={page==='guide'?'page':undefined}>Decision guide</button><button onClick={()=>setPage('progress')} aria-current={page==='progress'?'page':undefined}>Progress</button></nav></header><div id="content">
 {page==='guide'&&<DecisionGuide/>}{page==='progress'&&<section className="panel"><h2>Session progress</h2><p className="score">{progress.correct} / {progress.attempted} correct {progress.attempted?`(${Math.round(progress.correct/progress.attempted*100)}%)`:''}</p><h3>By mechanism</h3><ul>{answerMechanisms.map(m=>{const x=progress.byMechanism[m];return <li key={m}>{m}: {x?`${x.correct}/${x.attempted}`:'not attempted'}</li>})}</ul>{progress.mistakes.length>0&&<p>Recent concepts to revisit: {progress.mistakes.join(', ')}.</p>}<button className="danger" onClick={()=>setProgress(resetProgress())}>Reset progress</button></section>}
 {page==='practice'&&<><section className="controls panel" aria-label="Practice settings"><label>Reaction type<select value={mechanism} onChange={e=>{setMechanism(e.target.value as AnswerMechanism|'Mixed');setSelectedConcepts([])}}>{mechanismOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>{setDifficulty(e.target.value as Difficulty);setSelectedConcepts([])}}>{difficulties.map(x=><option key={x}>{x}</option>)}</select></label><fieldset><legend>Focus concepts (optional)</legend>{concepts.map(c=><label className="check" key={c}><input type="checkbox" disabled={!availableConcepts.has(c)} checked={selectedConcepts.includes(c)} onChange={()=>chooseConcept(c)}/>{c}</label>)}</fieldset></section>
 <article className="problem panel"><div className="problem-top"><div><p className="eyebrow">{problem.difficulty} · {problem.title}</p><h2>Analyze this reaction</h2></div><span className="tag">Choose, then draw</span></div><div className="reaction"><div><h3>Substrate</h3><Structure smiles={problem.substrateSmiles} label={problem.substrate}/><p>{problem.substrate} <span>({problem.substrateClass})</span></p></div><div className="arrow" aria-hidden="true">→</div><div className="conditions"><h3>Conditions</h3><dl><dt>Reagent</dt><dd>{problem.reagent}</dd><dt>Solvent</dt><dd>{problem.solvent}</dd><dt>Temperature</dt><dd>{problem.temperature}</dd><dt>Leaving group</dt><dd>{problem.leavingGroup}</dd></dl></div></div>
 <fieldset><legend>1. Which mechanism is most appropriate?</legend><div className="choices">{answerMechanisms.map(m=><label key={m}><input type="radio" name="mechanism" checked={answer.mechanism===m} onChange={()=>setAnswer({...answer,mechanism:m})}/>{m}</label>)}</div></fieldset>
 <fieldset disabled={!answer.mechanism}><legend>2. Draw the major product(s) in Ketcher</legend>{!answer.mechanism&&<p role="status">Choose SN1, SN2, or No reaction above before drawing.</p>}{answer.mechanism&&<Suspense fallback={<p>Loading chemical structure editor…</p>}><KetcherProductEditor key={problem.id} instruction={problem.intendedMechanism==='No reaction'?'No reaction: draw the unchanged starting material exactly as shown.':problem.products.filter(product=>product.role==='major').length>1?'Draw every major product as a separate disconnected structure on this canvas.':'Draw the major product. Do not draw a reagent or leaving group.'} onReady={getter=>setDrawingGetter(()=>getter)}/></Suspense>}</fieldset>
 <div className="actions"><button className="primary" onClick={submit}>Check my answer</button><button onClick={()=>setHint(x=>Math.min(x+1,4))}>Give me a hint</button><button onClick={()=>setHint(4)}>Show next step</button><button onClick={()=>setFeedback({level:'partial',points:0,message:`Full solution: ${problem.intendedMechanism}; major product${problem.products.filter(product=>product.role==='major').length===1?'':'s'}: ${problem.intendedMechanism==='No reaction'?'unchanged starting material':problem.products.filter(product=>product.role==='major').map(product=>product.name).join(' and ')}. ${problem.explanation}`})}>Show full solution</button><button onClick={next}>Next problem</button></div>{hint>0&&<aside className="hint"><strong>Hint {hint} of 4:</strong> {problem.hints[hint-1]}</aside>}{feedback&&<aside className={`feedback ${feedback.level}`} role="status"><strong>{feedback.level==='correct'?'Complete reasoning':feedback.level==='partial'?'Partly correct':'Try again'}</strong><p>{feedback.message}</p></aside>}</article></>}</div></main>}
